@include('includes/header')
@include('home/navbar')
@include('home/hero_carousel')
@include('home/car_listing')
@include('home/car_booking')
@include('home/partner_blog')
@include('home/review')
@include('includes/footer')
